config/routes.rb
Rails.application.routes.draw do
  get 'welcome_products/index'

  get 'welcome_products/search'

  resources :product_reviews
  get 'orders/archived_orders' => 'orders#archived_orders'
  resources :orders do
    get 'confirm'
    get 'deny'
    get 'archive'
    get 'dispatch_order'
  end
  get 'review/order_items'

  resources :addresses
  get 'cart/items'
  get 'cart/add'
  get 'cart/count'
  get 'cart/decrement_count'

  resources :products
  get 'welcome/index'

  devise_for :admins
  devise_for :users

   root 'welcome#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/controllers/orders_controller.rb
require 'json'
class OrdersController < ApplicationController

	before_action :authenticate_anyone?

	def index
		if current_user
			@orders = Order.all.where(placed_by: current_user.email).order(created_at: :desc).paginate(page: params[:page], per_page: 10)
		elsif current_admin
			@orders = Order.all.where(archived: false).order(created_at: :desc).paginate(page: params[:page], per_page: 10)
		end
	end

	def archived_orders
		if current_admin
			@orders = Order.all.where(archived: true).order(created_at: :desc).paginate(page: params[:page], per_page: 10)
		end
	end

	def show
	 	@order = Order.find(params[:id])
		items = @order.order_items
	  	items_to_find = []
	  	items.each do |k,v|
	  		items_to_find.push(k.to_i)
	  	end

	  	products = Product.find(items_to_find)

	  	@order_items = {}
	  	@total_price = 0
	  	products.each do |product|
	  		if items.has_key?(product.id.to_s)
	  			if items[product.id.to_s].to_i > 0
		  			@order_items[product.id.to_s] = [product.name,items[product.id.to_s],product.price*items[product.id.to_s].to_i]
		  			@total_price += product.price*items[product.id.to_s].to_i
		  		end
	  			# puts items[product.id.to_s].class
	  		end
	  	end
	end

	def create
		items = JSON.parse cookies[:cart_items]
		user = current_user
		address = user.addresses.find(params[:address_id])
		# print items.class
		shipping_to = address.name+', '+address.phone_number+', '+address.street+', '+address.locality+', '+address.city+', '+address.state+', '+address.pincode.to_s 
		order = Order.new(placed_by: current_user.email, shipping_to: shipping_to, order_items: items)
		if order.save
			cookies[:cart_items] = JSON. generate({})
			redirect_to order, notice: 'Order was successfully placed'
		else
			redirect_to products_path, notice: 'Something went wrong, please contact the team'
		end
	end

	def destroy
		order = Order.find(params[:order_id])
		order.destroy
		redirect_to orders_path, notice: 'Order was successfully destroyed.'
	end

	def archive
		order = Order.find(params[:order_id])
		if order.update(archived: true)
			redirect_to orders_path, notice: 'Order was successfully archived'
		else
			redirect_to order_id, notice: 'Something went wrong'
		end
	end

	def dispatch_order
		order = Order.find(params[:order_id])
		if order.update(dispatched: true)
			redirect_to orders_path, notice: 'Order was successfully dispatched'
		else
			redirect_to order_id, notice: 'Something went wrong'
		end
	end

	def confirm
		if Order.find(params[:order_id]).update(status: true)
			redirect_to orders_path, notice: "Order was confirmed"
		else
			redirect_to order_path, notice: "Something went wrong"
		end
	end
	def deny
		if Order.find(params[:order_id]).update(status: false)
			redirect_to orders_path, notice: "Order was denied"
		else
			redirect_to order_path, notice: "Something went wrong"
		end
	end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/archived_orders.html.erb
<div class="container">
	<% if admin_signed_in? %>
	<div class="row">
		<br/>
		<div class="col-lg-8 col-md-4">
		</div>
		<div class="col-lg-4 col-md-8 col-sm-12">
			<div class="btn-group" role="group" aria-label="Basic example">
			  <%= link_to "Archived", orders_archived_orders_path, class: "btn btn-secondary" %>
			  <%= link_to "All", orders_path, class: "btn btn-secondary" %>
			</div>
		</div>
	</div>
	<% end %>
	<br/>
	<div class="row">
	<% if !@orders.empty? %>
	<div class="table-responsive">
		<table class="table">
			<thead>
				<tr>
					<th>Placed By</th>
					<th>Placed On</th>
					<th>Status</th>
					<% if admin_signed_in? %>
					<th colspan="3"></th>
					<% else %>
					<th colspan="1"></th>
					<% end %>
				</tr>
			</thead>
			<tbody>
			<% @orders.each do |order| %>
			<% if order.archived %>
				<tr>
					<td><%= order.placed_by %></td>
					<td><%= order.created_at %></td>
					<% if order.status == nil %>
					<td>Order not confirmed yet.</td>
					<% elsif order.status == true %>
					<td>Order Confirmed</td>
					<% elsif order.status == false %>
					<td>Order has been denied. Contact the team</td>
					<% end %>
					<td><%= link_to "Show", order_path(order.id), class: "btn btn-primary btn-sm" %></td>
					<%if admin_signed_in? %>
					<td><%= link_to "Cofirm Order?", order_confirm_path(order_id: order.id), class: "btn btn-primary btn-sm", id: "confirmOrder" %></td>
					<td><%= link_to "Deny Order", order_deny_path(order_id: order.id), class: "btn btn-primary btn-sm", id: "denyOrder" %></td>
					<td><%= link_to "Archive Order", order_archive_path(order_id: order.id), class: "btn btn-primary btn-sm", id: "archiveOrder" %></td>
					<td><%= link_to "Dispatch Order", order_dispatch_order_path(order_id: order.id), class: "btn btn-primary btn-sm", id: "dispatchOrder" %></td>
					<td><%= link_to "Delete", order, class: "btn btn-primary btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %></td>
					<% end %>
				</tr>
			<% end %>
			<% end %>
			</tbody>
		</table>
		</div>
		<div>
		<center><%= will_paginate @orders %></center>
		<% else %>
			<center><p> No order Yet </p></center>
		<% end %>
	</div>
</div>

app/views/orders/index.html.erb
<div class="container">
	<% if admin_signed_in? %>
	<div class="row">
		<br/>
		<div class="col-lg-8 col-md-4">
		</div>
		<div class="col-lg-4 col-md-8 col-sm-12">
			<div class="btn-group" role="group" aria-label="Basic example">
			  <%= link_to "Archived", orders_archived_orders_path, class: "btn btn-secondary" %>
			  <%= link_to "All", orders_path, class: "btn btn-secondary" %>
			</div>
		</div>
	</div>
	<% end %>
	<br/>
	<div class="row">
	<% if !@orders.empty? %>
		<table class="striped responsive-table">
			<thead>
				<tr>
					<th>Placed By</th>
					<th>Placed On</th>
					<th>Status</th>
					<% if admin_signed_in? %>
					<th colspan="3"></th>
					<% else %>
					<th colspan="1"></th>
					<% end %>
				</tr>
			</thead>
			<tbody>
			<% @orders.each do |order| %>
			<% if !order.archived %>
				<tr>
					<td><%= order.placed_by %></td>
					<td><%= order.created_at %></td>
					<% if order.status == nil %>
					<td>Order not confirmed yet.</td>
					<% elsif order.status == true %>
					<td>Order Confirmed</td>
					<% elsif order.status == false %>
					<td>Order has been denied. Contact the team</td>
					<% end %>
					<td><%= link_to "Show", order_path(order.id), class: "btn btn-primary btn-sm" %></td>
					<%if admin_signed_in? %>
					<td><%= link_to "Cofirm Order?", order_confirm_path(order_id: order.id), class: "btn btn-primary btn-sm", id: "confirmOrder" %></td>
					<td><%= link_to "Deny Order", order_deny_path(order_id: order.id), class: "btn btn-primary btn-sm", id: "denyOrder" %></td>
					<td><%= link_to "Archive Order", order_archive_path(order_id: order.id), class: "btn btn-primary btn-sm", id: "archiveOrder" %></td>
					<td><%= link_to "Dispatch Order", order_dispatch_order_path(order_id: order.id), class: "btn btn-primary btn-sm", id: "dispatchOrder" %></td>
					<td><%= link_to "Delete", order, class: "btn btn-primary btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %></td>
					<% end %>
				</tr>
			<% end %>
			<% end %>
			</tbody>
		</table>
		<center><%= will_paginate @orders %></center>
	<% else %>
		<center><p> No order Yet </p></center>
	<% end %>
	</div>		
</div>


<!-- <div class="container">
	<div class="row">
		<ul class="collection">
		    <li class="collection-item avatar">
		      <img src="images/yuna.jpg" alt="" class="circle">
		      <span class="title">Title</span>
		      <p>First Line <br>
		         Second Line
		      </p>
		      <a href="#!" class="secondary-content"><i class="material-icons">grade</i></a>
		    </li>
		    <li class="collection-item avatar">
		      <i class="material-icons circle">folder</i>
		      <span class="title">Title</span>
		      <p>First Line <br>
		         Second Line
		      </p>
		      <a href="#!" class="secondary-content"><i class="material-icons">grade</i></a>
		    </li>
		    <li class="collection-item avatar">
		      <i class="material-icons circle green">insert_chart</i>
		      <span class="title">Title</span>
		      <p>First Line <br>
		         Second Line
		      </p>
		      <a href="#!" class="secondary-content"><i class="material-icons">grade</i></a>
		    </li>
		    <li class="collection-item avatar">
		      <i class="material-icons circle red">play_arrow</i>
		      <span class="title">Title</span>
		      <p>First Line <br>
		         Second Line
		      </p>
		      <a href="#!" class="secondary-content"><i class="material-icons">grade</i></a>
		    </li>
		</ul>
	</div>
</div>
 -->

app/views/orders/show.html.erb
<div class="container">
	<div class="row">
	<p> Placed by: <%= @order.placed_by %></p>
	<p> Shipping to: <%= @order.shipping_to %></p>
		<table class="table">
			<thead>
				<tr>
					<th>Item</th>
					<th>Quantity</th>
					<th>Price</th>
				</tr>
			</thead>
			<tbody>
				<% @order_items.each do |order_item| %>
					<tr>
						<td><%= order_item[1][0] %></td>
						<td><%= order_item[1][1] %></td>
						<td><%= order_item[1][2] %></td>
					</tr>
				<% end %>
					<tr>
						<td></td>
						<td><h4>Total: </h4></td>
						<td><%= @total_price %> Rs</td>
					</tr>
			</tbody>
		</table>
	</div>
</div>