config/routes.rb
Rails.application.routes.draw do
  get 'welcome_products/index'

  get 'welcome_products/search'

  resources :product_reviews
  get 'orders/archived_orders' => 'orders#archived_orders'
  resources :orders do
    get 'confirm'
    get 'deny'
    get 'archive'
    get 'dispatch_order'
  end
  get 'review/order_items'

  resources :addresses
  get 'cart/items'
  get 'cart/add'
  get 'cart/count'
  get 'cart/decrement_count'

  resources :products
  get 'welcome/index'

  devise_for :admins
  devise_for :users

   root 'welcome#index'

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /addresses
  # GET /addresses.json
  def index
    user = current_user
    @addresses = user.addresses.paginate(:page => params[:page])
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    user = current_user
    @address = user.addresses.build(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:name, :phone_number, :plot_no, :street, :locality, :city, :state, :pincode)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_form.html.erb
<%= simple_form_for(@address, remote: true) do |f| %>
  <% if f.error_notification %>
    <script type="text/javascript">Materialize.toast(' <%= f.error_notification %>', 3000, 'rounded')</script>
  <% end %>
  <div class="form-inputs">
    <%= f.input :name, required: true %>
    <%= f.input :phone_number, required: true %>
    <%= f.input :plot_no, required: true %>
    <%= f.input :street, required: true %>
    <%= f.input :locality, required: true %>
    <%= f.input :city, required: true %>
    <%= f.input :state, required: true %>
    <%= f.input :pincode, required: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<div class="container">
<div class="row">
<h1>Editing Address</h1>

<%= render 'form' %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>
</div>
</div>

app/views/addresses/index.html.erb
<div class="container">
<div class="row">
<h2> Choose an address </h2>
<% if @addresses %>
<p>Your Addresses<p>
<div class="table-responsive">
<table class="table">
  <thead>
    <tr>
      <th>Plot no</th>
      <th>Street</th>
      <th>City</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.plot_no %></td>
        <td><%= address.street %></td>
        <td><%= address.city %></td>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', edit_address_path(address) %></td>
        <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Choose', review_order_items_path(address_id: address.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div>
  <center><%= will_paginate @posts %></center>
</div>
<% else %>
  <h2>Please add an address</h2>
<% end %>
<br>

<%= link_to 'New Address', new_address_path %>
</div>
</div>

app/views/addresses/new.html.erb
<div class="container">
<div class="row">
<h1>New Address</h1>

<%= render 'form' %>

<%= link_to 'Back', addresses_path %>
</div>
</div>

app/views/addresses/show.html.erb
<p>
  <strong>Plot no:</strong>
  <%= @address.plot_no %>
</p>

<p>
  <strong>Street:</strong>
  <%= @address.street %>
</p>

<p>
  <strong>Locality:</strong>
  <%= @address.locality %>
</p>

<p>
  <strong>City:</strong>
  <%= @address.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @address.state %>
</p>

<p>
  <strong>Pincode:</strong>
  <%= @address.pincode %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>