config/routes.rb
Rails.application.routes.draw do
  get 'welcome_products/index'

  get 'welcome_products/search'

  resources :product_reviews
  get 'orders/archived_orders' => 'orders#archived_orders'
  resources :orders do
    get 'confirm'
    get 'deny'
    get 'archive'
    get 'dispatch_order'
  end
  get 'review/order_items'

  resources :addresses
  get 'cart/items'
  get 'cart/add'
  get 'cart/count'
  get 'cart/decrement_count'

  resources :products
  get 'welcome/index'

  devise_for :admins
  devise_for :users

   root 'welcome#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_attached_file :image, styles: { large: "300x160>", medium: "210x150>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  has_many :product_reviews
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:show, :index]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all.order('average_rating DESC, created_at').paginate(page: params[:page], per_page: 20)
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @reviews = @product.product_reviews.limit(10)
    @product_review = @product.product_reviews.build
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :description, :image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <% if f.error_notification %>
    <script type="text/javascript">Materialize.toast(' <%= f.error_notification %>', 3000, 'rounded')</script>
  <% end %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :price %>
    <%= f.input :description %>
    <%= f.input :image, label:"Upload Image", label_html: {class: "btn btn-primary"} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="container">
<div class="row">
<div class="col-lg-10">
<h1>Editing Product</h1>
<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>
</div>
</div>
</div>

app/views/products/index.html.erb
<div class="container">
  <br>
  <% if admin_signed_in? %>
  <%= link_to 'New Product', new_product_path, class: "waves-effect waves-light btn-large" %>
  <% end %>
  <div class="row">
    <% @products.each do |product| %>
      <div class="col l4 m6 s12">
        <div class="card product-card">
          <div class="card-image">
            <%= image_tag product.image.url(:medium), size: "210x150" %>
          </div>
          <div class="card-content">
          <span class="card-title activator grey-text text-darken-4" style="font-size:18px"><%= product.name %><i class="material-icons right">more_vert</i></span>
          <p>Price: <%= product.price %></p>
          <%  if product.average_rating > 0 %>
            <!-- <span><%= product.average_rating %></span> -->
            <% product.average_rating.floor.times do %>
              <i>&#9733;</i>
            <% end %>
          <% else %>
            <p>No rating</p>
          <% end %>
          </div>
          <div class="card-reveal">
            <span class="card-title grey-text text-darken-4"><%= product.name %><i class="material-icons right">close</i></span>
            <p><%= product.description %></p>
          </div>
          <div class="card-action">
              <div class="right">
                <%= link_to "Show", product, class: "waves-effect waves-light btn" %>
              </div>
              <div class="left">
                <%= link_to cart_add_path( id:  product.id ),remote: true, class: "btn-floating btn-large waves-effect waves-light red", onclick: "Materialize.toast('Added to cart', 4000)", id: "add_to_cart" do %>
                  <i class="material-icons" title="Add to Cart">add</i>
                <% end %>
              </div>
          </div><!-- 
          <div class="card-action">
            <% if admin_signed_in? %>
              <div class="right">
                <%= link_to "Edit", edit_product_path(product), class: "waves-effect waves-light btn"  %>
              </div>
              <div class="left">
                <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "waves-effect waves-light btn"  %>
              </div>
            <% end %>
          </div> -->
        </div>
      </div>
    <% end %>
  </div>
  <div class="row">
    <center><%= will_paginate @products %></center>
  </div>
</div>

<!-- 
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
      <% @products.each_with_index do |product, index| %>
          <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card">
              <div class="card-block">
                <%= image_tag product.image.url(:medium), class: "card-img-top img-responsive", size: "210x150" %>
                <h4 class="card-title"><%= product.name %></h4>
                <p class="card-text"><%= truncate(product.description, length: 20) %></p>
                <%= link_to "Add to cart", cart_add_path( id:  product.id ), remote: true, class: "btn btn-primary btn-lg btn-sm btn-md" %>
                <%= link_to "Show", product, class: "btn btn-success btn-sm btn-md btn-lg" %><br/><br/>
                <% if admin_signed_in? %>
                  <%= link_to "Edit", edit_product_path(product), class: "btn btn-info" %>
                  <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
                <% end %>
              </div>
              <ul class="list-group list-group-flush">
                <li class="list-group-item"><p> Price: <%= product.price %></p></li>
              </ul>
            </div>
          </div>
      <% end %>
  </div>
  <div class="row">
    <center><%= will_paginate @products %></center>
  </div>
</div>

<br>
<% if admin_signed_in? %>
<%= link_to 'New Product', new_product_path %>
<% end %>
 -->

app/views/products/new.html.erb
<div class="container">
<div class="row">
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>
</div>
</div>

app/views/products/show.html.erb
<div class="container">
	<div class="row">
	</div>
	<div class="row">
		<div class="col l4 m6 s12 pull-l1">
			<%= image_tag @product.image.url(:large), size: "320x220" %>
		</div>
		<div class="col l8 m6 s12">	
	      <ul class="collection with-header">
	        <li class="collection-header"><h4><%= @product.name %></h4></li>
	        <li class="collection-item"><p><%= @product.description %></p></li>
	        <li class="collection-item">
	        <%  if @product.average_rating > 0 %>
            <!-- <span><%= @product.average_rating %></span> -->
            	<% @product.average_rating.floor.times do %>
              		<i>&#9733;</i>
            	<% end %>
          	<% else %>
            	<p>No rating</p>
          	<% end %>
          	</li>
	        <li class="collection-item"><h5>Price: <%= @product.price %></h5></li>
	        <li class="collection-item"><%= link_to "Add to cart", cart_add_path( id:  @product.id ), remote: true, class: "waves-effect waves-light btn-large" %></li>
	      </ul>
		</div>
	</div>
	<div class="row">
    <div class="col l12 s12">
      <ul class="tabs">
        <li class="tab col s3"><a class="active" href="#reviews">Review</a></li>
        <li class="tab col s3"><a href="#specifications">Specification</a></li>
      </ul>
    </div>
    <div id="reviews" class="col l12 md12 s12">
	    <% if user_signed_in? %>
	    <div class="container">
		    <div class="row">
		    	<%= render 'product_reviews/form' %>
		    </div>
	    </div>
	    <% end %>
    	<div class="row">
    	<% @reviews.each do |review| %>
		<ul class="collection">
			    <li class="collection-item avatar">
			    <i class="material-icons circle green">insert_chart</i>
			      <span class="title"><%= review.user_name %></span>
			      <p>
			      	<%= review.review %>
			      </p>
			      <p class="secondary-content"><%= review.rating %></p>
			    </li>      
		</ul>
		<% end %>
    	</div>
    </div>
    <div id="specifications" class="col s12">
    	<div class="row">
	    	<p>
	    		And this is for specifications
	    	</p>
    	</div>
    </div>
  </div> 
</div>


<!-- 


<p><%= image_tag @product.image.url(:large) %></p>
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>
<%= link_to "Add to cart", cart_add_path( id:  @product.id ), remote: true, class: "btn btn-primary" %>
<% if admin_signed_in? %>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
<% end %>
 -->