config/routes.rb
Rails.application.routes.draw do
  get 'welcome_products/index'

  get 'welcome_products/search'

  resources :product_reviews
  get 'orders/archived_orders' => 'orders#archived_orders'
  resources :orders do
    get 'confirm'
    get 'deny'
    get 'archive'
    get 'dispatch_order'
  end
  get 'review/order_items'

  resources :addresses
  get 'cart/items'
  get 'cart/add'
  get 'cart/count'
  get 'cart/decrement_count'

  resources :products
  get 'welcome/index'

  devise_for :admins
  devise_for :users

   root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="manifest" href="/manifest.json">
   <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="https://www.atlasestateagents.co.uk/javascript/tether.min.js"></script><!-- Tether for Bootstrap --> 
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if params[:controller] != "welcome" %>
    <div class="navbar-fixed">
       <nav>
        <div class="nav-wrapper">
          <a href="#!" class="brand-logo">Demo</a>
          <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
          <ul class="right hide-on-med-and-down">
            <li ><%= link_to "Products", products_path %></li>
        		<li >
        		<%= link_to cart_items_path do %>
        			Cart <span class="badge" style="color:black"></span>
        		<% end %>
        		<!-- <a class="modal-trigger" href="#cart_items" id="open_cart">Cart</a> -->
        			<!-- Cart <span class="badge" id="cart_counter" style="color:black"></span> -->
        			<!-- Cart <span class="badge" style="color:black"></span> -->
        		</li>
      	  	<% if user_signed_in? %>
        	  	<li ><%= link_to "My Orders", orders_path %></li>
        	    <li ><%= link_to "Edit Password", edit_user_registration_path %></li>
        	    <li ><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
      	    <% elsif admin_signed_in? %>
        	    <li ><%= link_to "Orders", orders_path %></li>
        	    <li ><%= link_to "Sign Out", destroy_admin_session_path, method: :delete %></li>
      	    <% else %>
        	  	<li ><%= link_to "Sign In", new_user_session_path %></li>
        	    <li ><%= link_to "Register", new_user_registration_path %></li>
      	    <% end %>
          </ul>
          <ul class="side-nav" id="mobile-demo">
            <li ><%= link_to "Products", products_path %></li>
        		<li >
        			<%= link_to cart_items_path do %>
        				Cart <span class="badge" id="cart_counter_mobile_nav" style="color:black"></span>
        			<% end %>
        			<!-- <a class="modal-trigger" href="#cart_items" id="open_cart">Cart</a> -->
        		</li>
      	  	<% if user_signed_in? %>
        	  	<li ><%= link_to "My Orders", orders_path %></li>
        	    <li ><%= link_to "Edit Password", edit_user_registration_path %></li>
        	    <li ><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
      	    <% elsif admin_signed_in? %>
        	    <li ><%= link_to "Orders", orders_path %></li>
        	    <li ><%= link_to "Sign Out", destroy_admin_session_path, method: :delete %></li>
      	    <% else %>
        	  	<li ><%= link_to "Sign In", new_user_session_path %></li>
        	    <li ><%= link_to "Register", new_user_registration_path %></li>
      	    <% end %>
          </ul>
        </div>
      </nav>
    </div>
  <% end %>
  <% if notice %>
  	<script type="text/javascript">Materialize.toast('<%= notice %>', 3000)</script>
  <% end %>
  <% if alert %>
  	<script type="text/javascript">Materialize.toast('<%= alert %>', 3000)</script>
  <% end %>
  <%= yield %>
  <!-- <div id="cart_items" class="modal bottom-sheet">
  	<div class="modal-content">
  		<h4>Cart</h4>
  		<table>
  		<thead>
  			<tr>
  				<th>Item</th>
  				<th>Quantity</th>
  				<th>Price</th>
  			</tr>
  		</thead>
  		<tbody>

  		</tbody>
  		</table>
  	</div>
  	<div class="modal-footer">
  		<a id="close_cart">Close</a>
  	</div>
  </div> -->
</body>
<footer class="footer">
	<div class="container">
		<p class="text-muted">Parts Shop &copy</i>
		</p>
	</div>
</footer>
</html>